### ISSUE TITLE
GlotPress/Traduttore support

### ISSUE THREAD

**Issue by Biont** [inpsyde/wp-translation-downloader#2]
It would be immensely practical if this package would be able to check arbitrary [GlotPress](https://github.com/GlotPress/GlotPress-WP) instances for translations of packages. This would make it much easier to deploy private packages while maintaining a convenient translation workflow for them.

Please keep in mind that [Traduttore](https://github.com/wearerequired/traduttore) may be used to customize existing translations of official .org-plugins, so there needs to be a way to address collisions in a predictable way.

**Comment by Chrico** [comment]
added support for GlotPress API. Please have a look at the documentation.

**Comment by Chrico** [comment]
This issue is now done and support for self-hosted GlotPress is included in version 1.0 of `wp-translation-downloader`.

**Comment by j-falk** [comment]
I have read through the documentation at https://github.com/inpsyde/wp-translation-downloader#custom-glotpress-installations and have tried to get this working but don't really follow how this should work.

Here is an example:

- We have our own glotpress install setup at for example http://glotpress.example.org/
- There we have a project setup to translate a plugin to Norwegian, so the url to edit that project in Glotpress is then https://glotpress.example.org/projects/plugin-example/no/default/

In the documentation there is an example of defining translations from an external glotpress installation as `"wpackagist-plugin/*": "https://my-glotpress-instance.tld/plugins/%projectName%?version=%packageVersion%"`. But what is for example plugins in that url? Plugins is not even something that Glotpress cares about, they only have different projects?

Would very much appreciate the help with getting this working.

Thanks!

**Comment by Chrico** [comment]
Hey @j-falk 

Thanks for your question. We're using currently a selfhosted GlotPress as well for our private and custom Plugins/Themes/Libraries. 

Normally in GlotPress each project has an URL like `https://glotpress.example.com/projects/{projectName}/` to manage languages. The API to fetch entires for this project is available in `http://glotpress.example.com/api/translations/{projectName}`.

The example is just using for the sake of "simplicity" the `wpackagist-plugin/*`-match to show, that you can overwrite "officials" and ship your own translations for a Plugin instead of fetching it from WordPress.org API :)

**Comment by kimmenbert** [comment]
Hey,

Trying to get this to work for a single plugin in a selfhosted GlotPress installation.

composer.json content:
```
"require": {
    "composer/installers": "^1.11",
    "inpsyde/wp-translation-downloader": "^2.0",
    "wpackagist-plugin/woocommerce": "^5.2"
},
"extra": {
    "wp-translation-downloader": {
        "languages": [
            "nb_NO",
            "nb"
        ],
        "directory": "public/wp-content/languages",
        "api": {
            "names": {
                "wpackagist-plugin/woocommerce": "https://glotpress.example.com/api/projects/woocommerce/nb/woocommerce/"
            }
        }
    }
}
```

Been trying different API endpoints with no great success, including:
* /api/translations/woocommerce .. as you noted above. There does not seem to be a translations route in the API?
* /api/plugins/woocommerce .. as the readme suggests
* /api/woocommerce/ .. because looking at routes in GlotPress this (written correctly) seems to route to the function translations_get

The translation I'm trying to fetch is setup like this:

![image](https://user-images.githubusercontent.com/4253817/117491029-f0bbc400-af6f-11eb-8d08-eba1c0a2021e.png)

But always ending up with "found 0 translations"

Any chance that I could get a fully working example I could try to recreate myself?

GlotPress plugin version 2.3.1
inpsyde/wp-translation-downloader 2.0.3

**Comment by Chrico** [comment]
Hey 👋 

The configuration should look like following 

```json
"require": {
    "composer/installers": "^1.11",
    "inpsyde/wp-translation-downloader": "^2.0",
    "wpackagist-plugin/woocommerce": "^5.2"
},
"extra": {
    "wp-translation-downloader": {
        "languages": [
            "nb_NO",
            "nb"
        ],
        "directory": "public/wp-content/languages",
        "api": {
            "names": {
                "wpackagist-plugin/woocommerce": "https://glotpress.example.com/api/translations/woocommerce"
            }
        }
    }
}
```

*[!] Note:* The last URL piece "woocomerce" is the name of your translation project in GlotPress.

The URL structure for GlotPress is following:

- **Edit your project translations:** https://glotpress.example.com/projects/{project-name}/
- **API for your project:** https://glotpress.example.com/api/translations/{project-name}/

You need to provide the API-Endpoint for `inpsyde/wp-translation-downloader` :) 

If the API URL does not work for you, you might need to check your logs or rewrite rules. We're using following 2 Plugins on our custom GlotPress installation:

```json
"glotpress/glotpress-wp": "dev-develop#0c395a7a8f37ab3b5ebafd2b239c74392e5177f9",
"wearerequired/traduttore": "^3.0",
```

But we're also running a Multisite (multiple projects seperated by 1 project = 1 blog).

**Comment by kimmenbert** [comment]
Wow, thanks for that quick reply.
You say: You need to provide the API-Endpoint for `inpsyde/wp-translation-downloader`

What do you mean by this?
On the selfhosted GlotPress, do we need to do more than just having the GlotPress plugin installed, with projects and translations?

--
Update:
Seems like Traduttore was the missing component to make this work, since Traddutore has the wanted API endpoint.

Now I just have to figure out how to make quick updates to a translation in glotpress, and have it available as a language update in composer. Currently it just gets version 1 every time, so it uses the locally cached version of the language instead of getting updates.
